### PR TITLE
Add and_expr and or_expr

### PR DESCRIPTION
**Pull request by jmaitrehenry**

### CODE REVIEW

**Comment by rj33** [comment]
I'm not sure how far the code based has moved on since this PR was made, but I'll also really like the convenience of having these *_expr calls on expression objects. Is this still being considered for a future milestone?

**Comment by hiddentao** [comment]
A rewrite of the expression builder in concert with the query builders is needed. I've added this work to the v5 roadmap - #201

**Comment by hiddentao** [comment]
v5 is now out. Expressions now can be nested infinitely:

```js
squel.expr()
    .and("test = 3")
    .and(
        squel.expr()
            .or("inner = 1")
            .or("inner = 2")
    )
    .or(
        squel.expr()
            .and("inner = ?", 3)
            .and("inner = ?", 4)
            .or(
                squel.expr()
                    .and("inner IN ?", ['str1', 'str2', null])
            )
    )
    .toString()

```

**Comment by hiddentao** [comment]
Will close this PR soon unless people object.

**Pull request closed without merging**
