### PR TITLE
Quote FROM table names if option is enabled

### PR DESCRIPTION
**Pull request by deltasquare4**
Fixes a bug where enabling `autoQuoteTableNames` did not quote the table name in `FROM` clause. This failed for me when using with postgres.

**Code:**
```
var squel = require('squel');

var query = squel.select({ autoQuoteTableNames: true })
.field('id')
.from('user', 'u')
.where('u.id = ?', 1)
.toString();

console.log(query);
```

**Before:**
```
SELECT id FROM user `u` WHERE (u.id = 1)
```

**After:**
```
SELECT id FROM `user` `u` WHERE (u.id = 1)
```

### CODE REVIEW

**Comment by deltasquare4** [comment]
Merged latest upstream master and rebuilt assets.

PS: @hiddentao I know it's written in the contribution guide, but should I really be generating the assets for the pull request? Seems like it'll generate conflicts for every new pull request merged.

**Comment by hiddentao** [comment]
Thanks! Made some changes to the code though so I ended up just fixing this along the way. 5.3.1 has it fixed for you :)

**Comment by hiddentao** [comment]
Btw, as for why we bundle the buitl output in the repo, it's for people who don't want to install via NPM and go straight for the repo instead. Because squel is designed for browser usage too.

**Comment by deltasquare4** [comment]
Makes sense. Thank you 👍

**Pull request closed without merging**
