### PR TITLE
Added yarn file

### PR DESCRIPTION
**Pull request by munir131**

### CODE REVIEW

**Comment by hiddentao** [comment]
Why does Squel need a Yarn file?

**Comment by munir131** [comment]
@hiddentao Many developers are now switched to yarn for manage packages. yarn.lock will lock dependent lib when yarn install squel. All well known npm lib now adding yarn.lock file.
Related post: https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all

**Comment by hiddentao** [comment]
Yeah, but since squel only has dev dependencies, what benefit does a 
yarn.lock provide ?

---
Director
HiddenTao Ltd

www.hiddentao.com

(Sent from my mobile, apologies for brevity)

**Comment by munir131** [comment]
Ah. I haven't noticed that all dependencies are dev only. Then yarn.lock not needed.

**Pull request closed without merging**
