### PR TITLE
CASE Expressions, AS at table alias

### PR DESCRIPTION
**Pull request by SergeS**
- Added case expressions (#43) as separate type (As they are completely different that anything else there). Simple usage can be found in tests for them
- Allowed field function to take case expression as field
- Added aggregation option to field - So it can aggregate result of case expression (Or something else in future) `...field(... , ... , {aggreagtion : 'sum'})` for example
- Added option to add 'AS' keyword to table alias. This was the problem for Amazon Redshift (Which is based on older Postgresql)

### CODE REVIEW

**Comment by hiddentao** [comment]
Awesome PR, thanks. Just a couple of minor points I noticed - hope you agree.

**Comment by SergeS** [comment]
Hi, thanks for your review, updated code

**Comment by hiddentao** [comment]
Excellent, thankyou  :)

**Comment by hiddentao** [comment]
Published + added to API docs.

**Pull request merged**
