### PR TITLE
Enable limit to be 0

### PR DESCRIPTION
**Pull request by sqren**
It is currently not possible to supply a limit of 0. The following query:

```
squel.select().from('myTable').limit(0)
```

**Before:**
`SELECT * FROM myTable`

**After:**
`SELECT * FROM myTable LIMIT 0`

The current implementation will result in every row being returned, where the developer expects zero rows to be returned. This is a bit surprising, especially since `LIMIT 0` is valid sql.

Another approach would be to throw an error. That would at least make the developer aware.

### CODE REVIEW

**Comment by sqren** [comment]
Sorry, the current behaviour is correct.

**Comment by hiddentao** [comment]
No problem.

**Comment by sqren** [comment]
@hiddentao Thanks for your quick response. I just change my PR slightly. I realized that I can (and should) never call the database with a LIMIT 0 clause (it doesn't really make sense).
But the current implementation is also a bit surprising, as I write above.

**Comment by hiddentao** [comment]
Thanks!

**Pull request merged**
